---

- name: Download Stash
  get_url: url={{ stashUrl }}
           dest=/tmp
  sudo: yes

- name: Set Perms on Stash File
  file: path=/tmp/{{ stashExec }}
        owner=root
        group=root
        mode=0777  
  sudo: yes
 
- name: Copy Stash Template
  template: src=response.varfile.j2
            dest=/tmp/response.varfile
  sudo: yes

- name: Install Stash
  raw: /tmp/{{ stashExec }} -q -varfile /tmp/response.varfile
  sudo: yes

- name: Copy Stash init.d File
  template: src=stash.init.d.j2
            dest=/etc/init.d/stash
  sudo: yes

- name: get direcotry listing for debug
  raw: ls -al {{ stashData }}
  register: listing

- debug: var=listing

- name: Download MySQL Connector
  get_url: url={{ mysqlConnectorUrl }}
           dest={{ stashData }}/lib/{{ mysqlConnectorJar }}
  sudo: yes

- name: stop stash
  raw: cd /opt/atlassian/stash/3.7.1/bin && ./stop-stash.sh
  sudo: yes

- name: start stash
  raw: cd /opt/atlassian/stash/3.7.1/bin && ./start-stash.sh
  sudo: yes
