---

- name: Set up git repository
  apt_repository: repo='ppa:git-core/ppa'
  sudo: yes

- name: install git
  apt: name=git
       update_cache=yes
       state=latest

- name: Download Stash
  get_url: url={{ stashUrl }}
           dest=/tmp
  sudo: yes

- name: Set Perms on Stash File
  file: path=/tmp/{{ stashExec }}
        owner=root
        group=root
        mode=0777  
  sudo: yes
 
- name: Copy Stash Template
  template: src=response.varfile.j2
            dest=/tmp/response.varfile
  sudo: yes

- name: Install Stash
  raw: /tmp/{{ stashExec }} -q -varfile /tmp/response.varfile
  sudo: yes

- name: Create Stash Lib
  file: path={{ stashHome }}/lib
        owner=atlstash
        group=atlstash
        state=directory
  sudo: yes
 
- name: Copy Stash init.d File
  template: src=stash.init.d.j2
            dest=/etc/init.d/stash
  sudo: yes

- name: Download MySQL Connector
  get_url: url={{ mysqlConnectorUrl }}
           dest={{ stashData }}/lib/{{ mysqlConnectorJar }}
  sudo: yes

- name: stop stash
  raw: "{{ stashData }}/bin/stop-stash.sh"
  sudo_user: atlstash
  sudo: yes

- name: start stash
  raw: "{{ stashData }}/bin/start-stash.sh"
  sudo_user: atlstash
  sudo: yes
